# vooruit kijken

* Over twee jaar zie ik mezelf graag mijn vaardigheden en kennis op het gebied van de data science en life science verder ontwikkelen. Daarom overweeg ik om een Master Projectmanagement te volgen om mijn expertise te vergroten en mijn carrière vooruit te helpen.


* In de toekomst wil ik graag mijn kennis in de wetenschap gebruiken om de kwaliteit van het leven van de mensen in het algemeen en specifiek van de patienten verbeteren door het begeleiden van onderzoeks projecten. 


* Op dit moment ben ik actief bezig met het vergroten van mijn kennis en vaardigheden om de projecten goed te kunnen regelen en duidelijke plannen maken. 

* De volgende vaardigheid die ik graag zou willen leren naast leiderschapsvaardigheid, is het uitvoeren van NGS-analyses en het beheersen van HLA-typing R-tools om de genetische variaties te bestuderen die verband houden met ziekten, zoals kanker, auto-immuunziekten en genetische aandoeningen. Dit kan leiden tot een dieper inzicht in de oorzaken van ziekten en nieuwe behandelingsmogelijkheden. 

* De dag indeling voor het leren van hlar tools:
Dag 1: Data zoeken en Data cleaning and allele level analysis

Dag 2: IAllele clean and mis-match (functies: CleanAllele, valAlleleMism)

Dag 3: Eplet mismatch (functies: CalEpletMHCI, CalEpletMHCII, imputation)

Dag 4: other functionalities (functies: count of mis-match, CalAlleleTopN, CalAlleleMismFreq )

