# SQL
Dit opdracht wordt de Structured Query Language - or SQL programmeertaal gebruikt voor het beheren van relationele databases. Met SQL wordt verschillende bewerkingen op de flu and dengue data uitgevoerd, zoals het maken en wijzigen van databasestructuren zoals tabellen toevoegen en het manipuleren van gegevens binnen die structuren.


```{r, libraries}
library(tidyverse)
library(readxl)
library(dslabs)
library(stringr)
library(data.table)
library(tidyverse)
library(here)
library(dslabs)
library(grid)
library(readr)
library(RPostgreSQL)
library(gridExtra)
library(ggpubr)
library(stringr)
library(png)
library(DT)
library(ggplot2)

```


```{r}
#The flu, the dengue en gapminder packages loaden

##flu data
data_flu <- read_csv("https://raw.githubusercontent.com/DataScienceILC/tlsc-dsfb26v-20_workflows/main/data/flu_data.csv", skip = 10)

head(data_flu)

##dengue data
data_dengue <- read_csv("https://raw.githubusercontent.com/DataScienceILC/tlsc-dsfb26v-20_workflows/main/data/dengue_data.csv", skip = 10)

head(data_dengue)

##gapminder data
data_gapminder <- gapminder
head(gapminder)

```
Tidy data
```{r}
## De flu data tidy maken
data_flu_tidy <- data_flu %>% pivot_longer(cols = -Date, names_to = "country", values_to = "aantal_flu")

head(data_flu_tidy)

## De Date vriable vervangen door de year

data_flu_tidy$Date <- str_sub(data_flu_tidy$Date, start = 1, end = 4)
data_flu_tidy <- rename(data_flu_tidy, year = Date)
data_flu_tidy$country <- as.factor(data_flu_tidy$country)
data_flu_tidy$year <- as.integer(data_flu_tidy$year)

head(data_flu_tidy)

## De dengue data tidy maken
data_dengue_tidy <- data_dengue %>% pivot_longer(cols = -Date, names_to = "country", values_to = "aantal_dengue")

head(data_dengue_tidy)

## De Date vriable in dengue vervangen door de year
data_dengue_tidy$Date <- str_sub(data_dengue_tidy$Date, start = 1, end = 4)
data_dengue_tidy <- rename(data_dengue_tidy, year = Date)
data_dengue_tidy$year <- as.integer(data_dengue_tidy$year)
data_dengue_tidy$country <- as.factor(data_dengue_tidy$country)

head(data_dengue_tidy)

```

```{r, data opslaan}
## De flu data opslaan
write.csv(data_flu_tidy, "data_flu_tidy.csv", row.names = FALSE)

saveRDS(data_flu_tidy, "data_flu_tidy.rds")

## De dengue data opslaan

write.csv(data_dengue_tidy, "data_dengue_tidy.csv", row.names = FALSE)
saveRDS(data_dengue_tidy, "data_dengue_tidy.rds")


## Gapminder data opslaan
write.csv(data_gapminder, "data_gapminder.csv", row.names = FALSE)
saveRDS(data_gapminder, "data_gapminder.rds")

```
